export enum IvrObjectTypeEnum {
  PHONE = 'phone',
  ANNOUNCE = 'announce',
  SMS = 'sms',
  HANGUP = 'hangup',
  MENU = 'menu',
  QUEUE = 'queue',
  RING_LIST = 'ring_list',
  TIMECONDITION = 'timecondition',
  FAX = 'fax',
  SHORTNUM = 'shortnum',
  BLACKLIST = 'blacklist',
  VOICEMAILBOX = 'voicemailbox',
  EXTERNALROUTING = 'externalrouting',
  FMC = 'fmc',
  CONFERENCE = 'conference',
  SPEECH = 'speech-recog',
  API = 'api',
  CHECK = 'check',
  SYNTHESIS = 'synthesis',
  SWITCH = 'switch',
  CODE = 'code',
  EXTNUM = 'extnum',
}
