---
include:
  - project: 'ci-cd/templates'
    ref: master
    file: 'build.shell.gitlab-ci.yml'
  - project: 'ci-cd/templates'
    ref: master
    file: 'lintv2.shell.gitlab-ci.yml'
  - project: 'ci-cd/templates'
    ref: master
    file: 'deployv2.shell.gitlab-ci.yml'
  - project: 'ci-cd/templates'
    ref: master
    file: 'dismiss.shell.gitlab-ci.yml'

.before:
  before_script:

stages:
  - build
  - lint
  - test
  - deploy
  - dismiss

# TEST
.test:
  tags:
    - docker
  image: node:20-alpine
  stage: test
  allow_failure: true

test_lint-and-type-coverage:
  extends: .test
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event" || $STAGE_PIPELINE == "true")
      changes:
        - 'app/**/*.ts'
  script:
    - cd app/ && npm ci
    - npm run lint
    - npm run type-coverage

# PROD
build_prod:
  extends: .build_prod
lint_prod:
  extends: .lint_prod
deploy_prod:
  extends: .deploy_prod
  rules:
  - if: $CI_COMMIT_REF_NAME == "master" && $STAGE_PIPELINE != "true"
    when: manual
dismiss_prod:
  extends: .dismiss_prod
  rules:
  - if: $CI_COMMIT_REF_NAME == "master" && $STAGE_PIPELINE != "true"
    when: manual

# EUPROD
build_euprod:
  extends: .build_euprod
lint_euprod:
  extends: .lint_euprod
deploy_euprod:
  extends: .deploy_euprod
  rules:
  - if: $CI_COMMIT_REF_NAME == "master" && $STAGE_PIPELINE != "true"
    when: manual
dismiss_euprod:
  extends: .dismiss_euprod
  rules:
    - if: $CI_COMMIT_REF_NAME == "master" && $STAGE_PIPELINE != "true"
      when: manual

# STAGE
build_stage:
  extends: .build_stage
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event" || $STAGE_PIPELINE == "true")
lint_stage:
  extends: .lint_stage
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event" || $STAGE_PIPELINE == "true")
deploy_stage:
  extends: .deploy_stage
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event" || $STAGE_PIPELINE == "true")
      when: manual
dismiss_stage:
  extends: .dismiss_stage
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event" || $STAGE_PIPELINE == "true")
      when: manual
