export enum LogTopic {
  Unknown = 'unknown',
  PaymentProcessed = 'payment processed',
  Init = 'init',
  Api = 'api',
  Adapter = 'adapter',
  Integration = 'integration',
  Config = 'config',
  Message = 'message',
  MessageCount = 'message-count',
  Rabbitmq = 'rabbitmq',
  Handler = 'handler',
  Timer = 'timer',
}

export enum LogSubTopic {
  Unknown = 'unknown',
  Rabbitmq = 'rabbitmq',
  Rest = 'rest',
  ScenarioTranslation = 'scenariotranslation',
  Telegram = 'telegram',
  Vk = 'vk',
  Viber = 'viber',
  Multichat = 'multichat',
  Jivo = 'jivo',
  Google = 'google',
  Common = 'common',
  McnWidget = 'mcn-widget',
  InfiniteLoopBan = 'infiniteloopban',
  Noinit = 'noinit',
  OldMessagesFix = 'OldMessagesFix',
  AnalyticsFix = 'AnalyticsFix',
  LongTimerEvent = 'LongTimerEvent',
  StatCall = 'StatCall',
  User = 'user',
  Client = 'client',
  Role = 'role',
}
