export enum Projects {
  'services' = 'services',
  'base' = 'base',
  'chatbots' = 'chatbots',
  'integration' = 'integration',
  'telephony' = 'telephony',
  'robocall_platform' = 'robocall',
  'mcn_ui_components' = 'mcn-ui-components',
  'calltracking' = 'calltracking',
  'messaging' = 'messaging',
  'addressbook' = 'addressbook',
  'shop' = 'shop',
  'shop_backend' = 'shop_backend',
  'notificator' = 'notificator',
  'topbar' = 'topbar',
}
