export const PROJECT_REPOSITORY_PROVIDER = Symbol('PROJECT_REPOSITORY_PROVIDER');
export const QUERY_PROJECT_REPOSITORY_PROVIDER = Symbol('QUERY_PROJECT_REPOSITORY_PROVIDER');
export const PROJECT_SERVICE_PROVIDER = Symbol('PROJECT_SERVICE_PROVIDER');
