{{- if not (eq .Values.global.env "dev") }}

{{- $chartname := printf "%s-%s" .Chart.Name $.Values.werf.env -}}
{{- $replicaCount := index .Values (.Values.global.env) "replicaCount" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    app: {{ .Chart.Name }}-api
spec:
  replicas: {{ $replicaCount }}
  serviceName: {{ .Chart.Name }}-api
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Chart.Name }}-api
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ .Chart.Name }}-api
        image: '{{ index .Values.werf.image $chartname }}'
        env:
        - name: PROJECT
          value: {{ printf "%s-%s" .Chart.Name (.Values.global.env)}}
        envFrom:
        - configMapRef:
            name: config-values
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          initialDelaySeconds: 30

{{- end }}
