{{- if not (eq .Values.global.env "dev") }}

{{- $apiChartName := printf "%s-%s" .Chart.Name .Values.global.env -}}
{{- $replicaCount := index .Values (.Values.global.env) "replicaCount" -}}
{{- $kafkaSecrets := index .Values (.Values.global.env) "kafkaSecrets" | default list -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    app: {{ .Chart.Name }}-api
spec:
  replicas: {{ $replicaCount }}
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Chart.Name }}-api
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ .Chart.Name }}-api
        image: {{ index .Values.werf.image $apiChartName }}
        env:
        - name: PROJECT
          value: {{ printf "%s-%s" .Chart.Name (.Values.global.env)}}
        {{- range $kafkaSecrets  }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: {{ .secretName }}
              key: {{ .secretKey }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: config-values
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          initialDelaySeconds: 30

{{- end }}
