{{- if not (eq .Values.global.env "dev") }}

{{- $replicaCount := index .Values (env "ENVNAME") "replicaCount" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    app: {{ .Chart.Name }}-api
spec:
  replicas: {{ $replicaCount }}
  serviceName: {{ .Chart.Name }}-api
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Chart.Name }}-api
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ .Chart.Name }}-api
{{ tuple (printf "%s-%s" .Chart.Name (env "ENVNAME")) . | include "werf_container_image" | indent 8 }}
        env:
        - name: PROJECT
          value: {{ printf "%s-%s" .Chart.Name (env "ENVNAME")}}
        envFrom:
        - configMapRef:
            name: config-values
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          initialDelaySeconds: 30

{{- end }}
