{{- if or (eq .Values.global.env "stage") (eq .Values.global.env "prod") (eq .Values.global.env "euprod") }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ci_url }}
    http:
      paths:
      - pathType: Prefix
        path: /api
        backend:
          service:
            name:  {{ .Chart.Name }}-api
            port:
              number:  3000
---
{{- end }}
