{{- if or (eq .Values.global.env "stage") (eq .Values.global.env "prod") (eq .Values.global.env "euprod") }}
{{- $domains := index .Values (env "ENVNAME") "additionalDomains"  -}}
{{- $hosts := list -}}
{{- range $domains }}
    {{- $hosts = append $hosts (printf "%s%s" (env "APPNAME") .) }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress-public
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_origin ~ '^https:\/\/(.*)?\.?({{ print (join "|" (prepend $domains (env "DOMAIN"))) }})$' ) {
        more_set_headers "Access-Control-Allow-Origin: $http_origin";
        more_set_headers "Access-Control-Allow-Credentials: true";
        more_set_headers "Access-Control-Expose-Headers: X-Products-Hash";
      }
      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' "$http_origin" always;
        add_header 'Access-Control-Allow-Credentials' "true" always;
        add_header 'Access-Control-Allow-Methods' "PUT, GET, POST, DELETE, OPTIONS" always;
        add_header 'Access-Control-Allow-Headers' "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,X-Products-Hash" always;
        add_header 'Access-Control-Max-Age' 1728000 always;
        return 204;
      }
spec:
  rules:
  {{- range prepend $hosts .Values.ci_url  }}
  - host: {{ . }}
    http:
      paths:
      - pathType: Prefix
        path: /api/public
        backend:
          service:
            name:   {{ $.Chart.Name }}-api
            port:
              number:  3000
  {{- end }}
---
{{- end }}
