---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    app: {{ .Chart.Name }}-api
spec:
  selector:
    app: {{ .Chart.Name }}-api
  ports:
  - name: {{ .Chart.Name }}-api
    port: 3000
    protocol: TCP
  - port: 8080
    name: {{ .Chart.Name }}-swagger
    protocol: TCP
    targetPort: 8080