---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    app: {{ .Chart.Name }}-api
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-api
  ports:
  - name: {{ .Chart.Name }}-api
    port: 3000
    protocol: TCP
