---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    app: {{ .Chart.Name }}-api
spec:
  selector:
    app: {{ .Chart.Name }}-api
  ports:
  - name: {{ .Chart.Name }}-api
    port: 3000
    protocol: TCP
  - port: 8080
    name: {{ .Chart.Name }}-swagger
    protocol: TCP
    targetPort: 8080
---
{{- if not (eq .Values.global.env "dev") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-front
  labels:
    app: {{ .Chart.Name }}-front
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-front
  ports:
  - name: {{ .Chart.Name }}-front
    port: 80
    protocol: TCP
---
{{- end }}
