{{- define "docs-deploy" }} {{- $ := index . 0 }} {{- with index . 1 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-docs
  labels:
    app: {{ .Chart.Name }}-docs
spec:
  replicas: 1
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-docs
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-docs
      annotations:
        checksum/configmap-nginx: '{{ include (print $.Template.BasePath "/020-config-nginx-prod.yaml") . | sha256sum }}'
    spec:
      containers:
      - name: {{ .Chart.Name }}-docs
      {{ tuple (printf "%s-%s-%s" .Chart.Name "docs" (env "ENVNAME")) . | werf_container_image | indent 2 }}
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          name: {{ .Chart.Name }}-nginx-conf
      volumes:
      - name: {{ .Chart.Name }}-nginx-conf
        configMap:
          name: {{ .Chart.Name }}-nginx-conf


{{- end }} {{- end }}
