export const REDIS_CLIENT_PROVIDER = Symbol('REDIS_CLIENT_PROVIDER');
export const REDLOCK_PROVIDER = Symbol('REDLOCK_PROVIDER');
export const IN_MEMORY_STORAGE_SERVICE_PROVIDER = Symbol('IN_MEMORY_STORAGE_SERVICE_PROVIDER');
