dev:
  replicaCount: 1
  keydbHost: keydb-dev
  keydbPort: 6379
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: glogvoip2.mcn.ru
  graylogPort: 12201
stage:
  replicaCount: 2
  keydbHost: keydb-stage
  keydbPort: 6379
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: glogvoip2.mcn.ru
  graylogPort: 12201
prod:
  replicaCount: 3
  keydbHost: keydb-prod
  keydbPort: 6379
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: glogvoip2.mcn.ru
  graylogPort: 12201
  additionalDomains:
    - .mcnmobile.ru
euprod:
  replicaCount: 3
  keydbHost: keydb-euprod
  keydbPort: 6379
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: graylog.kompaas.tech
  graylogPort: 12201
  additionalDomains:
    - .myinno.net
    - .cpaas.tech
