dev:
  replicaCount: 1
  keydbHost: keydb-dev
  keydbPort: 6379
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: glogvoip2.mcn.ru
  graylogPort: 12201
stage:
  replicaCount: 1
  keydbHost: keydb-stage
  keydbPort: 6379
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: glogvoip2.mcn.ru
  graylogPort: 12201
prod:
  replicaCount: 3
  keydbHost: keydb-prod
  keydbPort: 6379
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: glogvoip2.mcn.ru
  graylogPort: 12201
  additionalDomains:
    - .mcnmobile.ru
euprod:
  replicaCount: 3
  keydbHost: keydb-euprod
  keydbPort: 6379
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: graylog.kompaas.tech
  graylogPort: 12201
  additionalDomains:
    - .myinno.net
    - .cpaas.tech
dns:
  - prod: translator.example.org
    tls: example.org
    domain: example
  - prod: translator.myinno.net
    tls: translator.myinno.net
    domain: myinno
  - prod: translator.mcn.kz
    tls: translator.mcn.kz
    domain: mcn
  - prod: translator.mcn.kz
    tls: translator.mcn.kz
    domain: mcn
  - prod: translator.mcn.kz
    tls: translator.mcn.kz
    domain: mcn
  - prod: translator.mcn.kz
    tls: translator.mcn.kz
    domain: mcn
  - prod: translator.mcn.kz
    tls: translator.mcn.kz
    domain: mcn
