dev:
  redisHost: redis-dev
  redisPort: 6379
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: glogvoip2.mcn.ru
  graylogPort: 12201
stage:
  redisHost: redis-stage
  redisPort: 6379
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: glogvoip2.mcn.ru
  graylogPort: 12201
prod:
  redisHost: redis-prod
  redisPort: 6379
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: glogvoip2.mcn.ru
  graylogPort: 12201
euprod:
  redisHost: redis-euprod
  redisPort: 6379
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: glogvoip2.mcn.ru
  graylogPort: 12201
