dev:
  replicaCount: 1
  redisHost: redis
  redisPort: 6379
  redisSentinelHost: sentinel
  redisSentinelPort: 26379
  redisSentinelMasterName: mymaster
  redisCacheDatabase: 1
  redisStorageClass: standard
  redisStorage: 1Gi
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: glogvoip2.mcn.ru
  graylogPort: 12201
  kafkaBrokers: '["bootstrap-k8s-kafka-stage.mcnloc.ru:444"]'
  kafkaClientId: translator_api_dev
  kafkaGroupId: translator_api_dev
  postgresHost: eridanus4.mcn.ru
  postgresPort: 5432
stage:
  replicaCount: 1
  redisHost: redis
  redisPort: 6379
  redisSentinelHost: sentinel
  redisSentinelPort: 26379
  redisSentinelMasterName: mymaster
  redisCacheDatabase: 1
  redisStorageClass: local-path
  redisStorage: 1Gi
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: glogvoip2.mcn.ru
  graylogPort: 12201
  kafkaBrokers: '["bootstrap-k8s-kafka-stage.mcnloc.ru:444"]'
  kafkaClientId: translator_api_stage
  kafkaGroupId: translator_api_stage
  postgresHost: eridanus4.mcn.ru
  postgresPort: 5432
spd:
  replicaCount: 1
  redisHost: redis
  redisPort: 6379
  redisSentinelHost: sentinel
  redisSentinelPort: 26379
  redisSentinelMasterName: mymaster
  redisCacheDatabase: 1
  redisStorageClass: local-path
  redisStorage: 1Gi
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: glogvoip2.mcn.ru
  graylogPort: 12201
  kafkaBrokers: '["bootstrap-k8s-kafka-stage.mcnloc.ru:444"]'
  kafkaClientId: translator_api_spd1
  kafkaGroupId: translator_api_spd1
  postgresHost: eridanus4.mcn.ru
  postgresPort: 5432
prod:
  replicaCount: 3
  redisHost: redis
  redisPort: 6379
  redisSentinelHost: sentinel
  redisSentinelPort: 26379
  redisSentinelMasterName: mymaster
  redisCacheDatabase: 1
  redisStorageClass: csi-rbd-sc
  redisStorage: 1Gi
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: glogvoip2.mcn.ru
  graylogPort: 12201
  kafkaBrokers: '["bootstrap-k8s-kafka3.mcn.ru:444"]'
  kafkaClientId: translator_api
  kafkaGroupId: translator_api
  kafkaSecrets:
    - name: KAFKA_KEY
      secretName: prod-kafka3-cluster-ca-cert
      secretKey: vpbx-team.key
    - name: KAFKA_CRT
      secretName: prod-kafka3-cluster-ca-cert
      secretKey: vpbx-team.crt
    - name: CLUSTER_CRT
      secretName: prod-kafka3-cluster-ca-cert
      secretKey: cluster-ca.crt
  postgresHost: translatordb.veles.mcn.ru
  postgresPort: 54206
euprod:
  replicaCount: 3
  redisHost: redis
  redisPort: 6379
  redisSentinelHost: sentinel
  redisSentinelPort: 26379
  redisSentinelMasterName: mymaster
  redisCacheDatabase: 1
  redisStorageClass: csi-rbd-sc
  redisStorage: 1Gi
  pootleApiUrl: https://translate.mcn.ru/
  graylogHost: graylog.kompaas.tech
  graylogPort: 12201
  kafkaBrokers: '["mcn-kafka-cluster-eu-kafka-bootstrap.kafka:9092"]'
  kafkaClientId: translator_api
  kafkaGroupId: translator_api
dns:
  - prod: translator.myinno.net
    tls: translator.myinno.net
    domain: myinno
  - prod: translator.mcn.kz
    tls: translator.mcn.kz
    domain: mcn
