name: lint-pootle-validate-back-on-pr
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize
    paths:
      - 'lang/**.po'
jobs:
  pootle-validate:
    runs-on: ubuntu-22.04 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
        working-directory: 'api'
      - name: Run pootle validation
        run: npm run pootle-validate
        working-directory: 'api'