name: lint-coverage-types-back-on-pr
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize
    paths:
      - 'api/src/**.ts'
jobs:
  lint-scripts:
    runs-on: ubuntu-22.04 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
        working-directory: 'api'
      - name: Run Type Coverage
        run: npm run type-coverage
        working-directory: 'api'